#!/bin/sh

########################################################
# after visiting the URL generated by dropboxd
########################################################

dropbox start
dropbox lansync y
echo "Status: $(dropbox status)"

# exclude/filestatus must be run from within Dropbox dir
cd ~/Dropbox
dropbox exclude add Backgrounds Bookmarks Public
sleep 1s
echo
dropbox filestatus
echo
dropbox exclude
