#!/bin/sh

########################################################
# after visiting the URL generated by dropboxd
########################################################

# Dropbox shortcut/autostart for this user ONLY
echo '[ "$(pidof dropbox)" ] || dropbox start' >> ~/.profile
echo "alias dropbox='~/dropbox.py'" >> ~/.profile

. ~/.profile

sleep 1s

dropbox status

dropbox lansync y
dropbox exclude add Bookmarks Public Resume interfacelift
